version: "3.7"

services:
  main:
    container_name: main
    build:
      context: ./party-haan-be
      target: development
    volumes:
      - ./party-haan-be:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  client:
    container_name: client
    build:
      context: ./party-haan-react
      target: development
    volumes:
      - ./party-haan-react:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    command: npm start
    env_file:
      - .env
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
